
PYTHON := python

all : rings.png rings.pdf scatter.png scatter.pdf

rings.png rings.pdf : draw_circles.py
	$(PYTHON) draw_circles.py

scatter.png scatter.pdf : draw_scatter.py
	$(PYTHON) draw_scatter.py
